### PR TITLE
eslint setup

### PR DESCRIPTION
**Pull request by gustavnikolaj**
@Munter for your inspiration :-)

### CODE REVIEW

**Comment by papandreou** [comment]
Rebase and placed jshint with eslint and the eslint-config-onelint config.

@Munter, how would you feel about switching to 4 space indentation? :)

**Comment by Munter** [comment]
I do prefer 2 spaces indentation these days. I'm working on a small screen :)

**Comment by gustavnikolaj** [comment]
You could extend the onelint-config like this:

```js
module.exports = {
  extends: 'onelint',
  rules: {
    indent: [2, 2]
  }
};
```

Or swap to something else entirely, like https://github.com/Flet/semistandard - which is based on standard which is based on eslint. But it won't be compatible with most normal eslint setups.

**Comment by papandreou** [comment]
Good idea with the indent rule. Added that and fiddled around a bit, and it seems to lint OK now.

**Comment by Munter** [comment]
Awesome. eslint is certainly much better. I just still haven't had time to properly read the documentation and understand the configuration :)

**Pull request merged**
